version: '3.8'
services:
  # База данных
  db_postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: пароль
      POSTGRES_DB: app_db
      TZ: Asia/Irkutsk
    ports:
      - "54320:5432"
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  
  # REST API
  postgrest:
    image: postgrest/postgrest
    restart: always
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://root:пароль@db_postgres:5432/app_db
      PGRST_DB_ANON_ROLE: anonymous
      PGRST_DB_SCHEMA: public
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
    depends_on:
      - db_postgres
  
  #
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "5050:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://localhost:3000/

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

volumes:
  local_pgdata:
