version: '3.8'
services:
  db_postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    ports:
      - "54320:5432"
    volumes:
      - local_pgdata:/var/lib/postgresql/data

volumes:
  local_pgdata:
