// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package ui

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
//"fmt"
//"crypto-trading-bot/internal/models"
)

func StrategySettingsField() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div x-init=\"\n\t\tfields = {\n\t\t\t\twaves: {\n\t\t\t\t\tnum_clusters: 5,\n\t\t\t\t\tblock_size: 5,\n\t\t\t\t\toverlap: 4\n\t\t\t\t}\n\t\t\t}\n\t\teditableItem.config = editableItem.config || fields\n\t\"><button class=\"button\" @click=\"editableItem.config = fields\">Обновить поля</button><p>Waves</p><label>Количество кластеров</label> <input x-model=\"editableItem.config.waves.num_clusters\" type=\"number\"> <label>Размер блока в секундах</label> <input x-model=\"editableItem.config.waves.block_size\" type=\"number\"> <label>Перекрытие смежных блоков в секундах</label> <input x-model=\"editableItem.config.waves.overlap\" type=\"number\"></div><script>\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
